apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-ticker
  labels:
    app: crypto-ticker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: crypto-ticker
  template:
    metadata:
      labels:
        app: crypto-ticker
    spec:
      containers:
        - name: crypto-ticker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 