apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-ticker
  labels:
    app: crypto-ticker
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      app: crypto-ticker
  template:
    metadata:
      labels:
        app: crypto-ticker
    spec:
      serviceAccountName: crypto-ticker-sa
      containers:
        - name: crypto-ticker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-monitoring-config
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: {{ .Values.projectId }}
            {{- toYaml .Values.env | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }} 