apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: {{ if eq .Release.Name "crypto-ticker-staging" }}"crypto-ticker-staging-ip"{{ else }}"crypto-ticker-ip"{{ end }}
    networking.gke.io/load-balancer-type: "External"
spec:
  ingressClassName: gce
  rules:
  - host: {{ if eq .Release.Name "crypto-ticker-staging" }}crypto-ticker-staging-34-8-145-3.nip.io{{ else }}crypto-ticker-prod-34-49-17-144.nip.io{{ end }}
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 8080 