{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-monitoring-config
  labels:
    app: {{ .Release.Name }}
    environment: {{ .Values.environment }}
data:
  OTEL_PYTHON_CLOUD_TRACE_PROPAGATOR: "true"
  OTEL_SERVICE_NAME: "crypto-ticker-{{ .Values.environment }}"
{{- end }} 