{{- if eq .Release.Name "crypto-ticker-production" }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: gce-production
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: Helm
    environment: production
spec:
  controller: kubernetes.io/ingress-gce
{{- end }} 