apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ .Release.Name }}-backend-config"}'
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Release.Name }} 