apiVersion: v1
kind: Service
metadata:
  name: crypto-ticker
  labels:
    app: crypto-ticker
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: crypto-ticker 