apiVersion: v1
kind: ServiceAccount
metadata:
  name: crypto-ticker-sa
  annotations:
    iam.gke.io/gcp-service-account: crypto-ticker@${PROJECT_ID}.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: crypto-ticker
spec:
  displayName: "Crypto Ticker Service Account" 