grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - 3001-cs-7bc564a6-1c3a-4afa-8e1a-86a29dba4879.cs-us-east1-yeah.cloudshell.dev

prometheus:
  server:
    persistentVolume:
      size: 20Gi

tempo:
  persistence:
    size: 5Gi 
