grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.crypto-ticker.com

prometheus:
  server:
    persistentVolume:
      size: 20Gi

tempo:
  persistence:
    size: 5Gi 