replicaCount: 2

image:
  repository: nemesisrfl/crypto-ticker
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi

environment: production

rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 0

nodeSelector:
  cloud.google.com/gke-nodepool: prod-pool

tolerations:
  - key: "nodeType"
    operator: "Equal"
    value: "prod"
    effect: "PreferNoSchedule"

env:
  - name: PORT
    value: "8080"
  - name: ENVIRONMENT
    value: "production"
  - name: MB_LOGIN
    valueFrom:
      secretKeyRef:
        name: crypto-ticker-secrets
        key: mb_login
  - name: MB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: crypto-ticker-secrets
        key: mb_password 