# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "google" {
  project     = "entrevista-nemesisrfl"
  region      = "us-central1"
  credentials = "/home/dom/workspace/MB2025/terraform/credentials/service-account.json"
}

provider "helm" {
  kubernetes {
    config_path = "~/.kube/config"
  }
}

provider "kubernetes" {
  config_path = "~/.kube/config"
}
