loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  server:
    http_listen_port: 3100
  
persistence:
  enabled: false
  
resources:
  requests:
    memory: 128Mi
    cpu: 50m
  limits:
    memory: 256Mi

singleBinary:
  replicas: 1

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false

test:
  enabled: false 