server:
  persistentVolume:
    enabled: false

  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi

alertmanager:
  enabled: false

pushgateway:
  enabled: false 