kube-prometheus-stack:
  fullnameOverride: prometheus
  grafana:
    enabled: true
    service:
      type: ClusterIP
    persistence:
      enabled: true
      size: 10Gi
    additionalDataSources:
      - name: Tempo
        type: tempo
        url: http://tempo:3100
        access: proxy
  prometheus:
    prometheusSpec:
      retention: 15d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
      additionalScrapeConfigs:
        - job_name: 'crypto-ticker-staging'
          static_configs:
            - targets: ['crypto-ticker-staging:8080']
          labels:
            environment: staging
        - job_name: 'crypto-ticker-prod'
          static_configs:
            - targets: ['crypto-ticker-prod:8080']
          labels:
            environment: production
        - job_name: 'tempo'
          static_configs:
            - targets: ['tempo:3200']
          labels:
            environment: monitoring

tempo:
  enabled: true
  serviceMonitor:
    enabled: true
  persistence:
    enabled: true
    size: 10Gi
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
  config: |
    search_enabled: true
    metrics_generator:
      registry:
        external_labels:
          source: tempo
    receivers:
      otlp:
        protocols:
          grpc:
            include_metadata: true
          http:
            include_metadata: true

 