kube-prometheus-stack:
  fullnameOverride: prometheus
  grafana:
    enabled: true
    service:
      type: ClusterIP
    persistence:
      enabled: true
      size: 10Gi
    additionalDataSources:
      - name: Tempo
        type: tempo
        url: http://observability-tempo:3200
        access: proxy
  prometheus:
    prometheusSpec:
      retention: 15d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelector: {}
      podMonitorNamespaceSelector: {}
      podMonitorSelectorNilUsesHelmValues: false
      additionalScrapeConfigs:
        - job_name: prometheus
          static_configs:
            - targets:
              - localhost:9090

        - job_name: crypto-ticker-staging
          metrics_path: /metrics
          scheme: http
          static_configs:
            - targets:
              - crypto-ticker-staging:8080
          metric_relabel_configs:
            - source_labels: [__name__]
              target_label: environment
              replacement: staging

        - job_name: crypto-ticker-prod
          metrics_path: /metrics
          scheme: http
          static_configs:
            - targets:
              - crypto-ticker-prod:8080
          metric_relabel_configs:
            - source_labels: [__name__]
              target_label: environment
              replacement: production

        - job_name: tempo
          metrics_path: /metrics
          scheme: http
          static_configs:
            - targets:
              - observability-tempo:3200
          metric_relabel_configs:
            - source_labels: [__name__]
              target_label: environment
              replacement: monitoring

tempo:
  enabled: true
  serviceMonitor:
    enabled: true
  persistence:
    enabled: true
    size: 10Gi
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
  config: |
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"
    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1_000_000
      max_block_duration: 5m
    compactor:
      compaction:
        block_retention: 48h
    metrics_generator:
      registry:
        external_labels:
          source: tempo
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
  extraArgs:
    "search.enabled": "true"

 