replicaCount: 1

image:
  repository: nemesisrfl/crypto-ticker
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector:
  nodeType: staging:PreferNoSchedule

tolerations:
  - key: pool-type
    operator: Equal
    value: staging
    effect: PreferNoSchedule

env:
  - name: PORT
    value: "8080"
  - name: ENVIRONMENT
    value: "staging"
  - name: MB_LOGIN
    valueFrom:
      secretKeyRef:
        name: crypto-ticker-secrets
        key: mb_login
  - name: MB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: crypto-ticker-secrets
        key: mb_password 