name: CI/CD Pipeline

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

env:
  PROJECT_ID: entrevista-nemesisrfl
  GKE_CLUSTER: crypto-ticker-entrevista
  GKE_ZONE: us-central1-a
  DOCKER_IMAGE: nemesisrfl/crypto-ticker
  WORKING_IMAGE_SHA: b273aa8d5b802e784b4e96d24f49d0d0472c6f91
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull and retag working image as latest
      run: |
        docker pull ${{ env.DOCKER_IMAGE }}:${{ env.WORKING_IMAGE_SHA }}
        docker tag ${{ env.DOCKER_IMAGE }}:${{ env.WORKING_IMAGE_SHA }} ${{ env.DOCKER_IMAGE }}:latest
        docker push ${{ env.DOCKER_IMAGE }}:latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./app
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

  deploy-staging:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: http://staging.crypto-ticker.com  # Substitua pela URL real do seu ambiente de staging
    steps:
    - uses: actions/checkout@v2

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Get GKE credentials'
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.8.1'

    - name: Deploy to Staging
      run: |
        helm upgrade --install crypto-ticker-staging ./helm/crypto-ticker \
          -f ./helm/crypto-ticker/environments/staging/values.yaml \
          --set image.repository=${{ env.DOCKER_IMAGE }} \
          --set image.tag=${{ github.sha }}

  deploy-prod:
    needs: [build-and-push, deploy-staging]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://prod.crypto-ticker.com  # Substitua pela URL real do seu ambiente de produção
    steps:
    - uses: actions/checkout@v2

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Get GKE credentials'
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.8.1'

    - name: Deploy to Production
      run: |
        helm upgrade --install crypto-ticker-prod ./helm/crypto-ticker \
          -f ./helm/crypto-ticker/environments/prod/values.yaml \
          --set image.repository=${{ env.DOCKER_IMAGE }} \
          --set image.tag=${{ github.sha }} 